### ISSUE TITLE
Function definition regex issues

### ISSUE THREAD

**Issue by chere005** [ViktorQvarfordt/Sublime-WolframLanguage#2]
try the following:

```
f[x_, OptionsPattern[]] :=
 {x, OptionValue[a]}
```

It no longer looks like a function definition because of the right bracket from ]

Also consider that if the := is on a different line like:

```
foo[
    bar_Integer,
    bas_Real
] :=
```

Lastly it would be nice if when typing a variable using Blank, anything on the right showed up like a function

foo_Integer <- foo_ should look like a var name, and "Integer" should look like a function..

Also don't forget about cases like
```
foo[bar:(_Integer | _Real)] :=
foo[bar_?PositiveQ] :=
```

Blank patterns show up all over the place.. It would be nice if something like the following had some highlighting for x___
```
StringCases[foo, {"<" ~~ x___ ~~ ">" :> x}]
```

**Comment by ViktorQvarfordt** [comment]
Thanks for opening this issue!

1. `f[x_, OptionsPattern[]] :=` is now fixed in 49b4cd3

2. `:=` on a different line. This cannot be fixed because the `:=` is scanned for with regex lookahead, which only matches until end of line. Many other language syntax highlighters have this issue (such as the built in syntax highlighting for JavaScript). See further discussion of this issue for the Julia language [here](https://github.com/JuliaEditorSupport/Julia-sublime/issues/33#issuecomment-243394992).

3. Regarding the other issues you raise, I'm not I see how these should be highlighted. Ideally you could give failing tests in [syntax_test.wl](https://github.com/ViktorQvarfordt/Sublime-WolframLanguage/blob/master/syntax_test_wolfram_language.wl) by opening a PR with failing tests, in this way it is much easier for me to provide a fix, and you can have a go at it if you want as well.

**Comment by ViktorQvarfordt** [comment]
Any updates on this?

**Comment by chere005** [comment]
Haven't had any time to look at this, sorry. I will try to in the next few
weeks. The other fixes were necessary for me to keep working effectively :)

**Comment by Shigma** [comment]
Is the problem solved? @chere005

**Comment by chere005** [comment]
This problem is solved after most recent PRs. Yay!
